<%@ Page Title="" Language="C#" MasterPageFile="~/FlyingFishMasterPage.master" AutoEventWireup="true" CodeFile="ReportsMainPage.aspx.cs" Inherits="Reports_ReportEntry" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="content" Runat="Server">
<h2>Reports</h2>

<p>FlyingFish can generate 3 types of reports: Timesheet Summary Report, Earned Value Report, Workpackage Status Report. The first two reports are generated by the Project Manager while the third report is generated by the Responsible Engineer and requires some input.
</p>
<p>All the reports can be created for any cut-off date (previous or future). The cut-off date means the report will only include data that is on or before that date. When dealing with timesheets, only approved timesheets are included. This means that if the cut-off date is in the middle of the week, the cut-off date is rolled back to the previous Friday.
</p>

<h4>Timesheet Summary Report</h4>
<p>
The Project Manager can choose a project and specify the cut-off date, then generate the report. The report summarizes the hours spent by each employee on each work package of the given project. Based on the cut-off date, the report indicates the hours an employee spent on a work package for the past 4 weeks and the past 4 months, as well as the total time since the project start.
</p>

<h4>Workpackage Status Report</h4>
<p>
The Responsible Engineer can choose a project, a workpackage, and a cut-off date. This report then describes a work package’s progress in terms of labour, issues, and plans for the previous week and the current week for the given cut-off date. The labour data includes the actual work done, the estimate of the work remaining, and the estimate of the total work at completion in days and dollars for each employee assigned to the workpackage. The responsible engineer can specify either of the two estimates (to completion or at completion) and the system will calculate the missing value.
</p>

<h4>Earned Value Report (EVR)</h4>
<p>
The Project Manager can choose a project and a cut-off date, and then generate the EVR. The EVR compares the labour estimates to the separate, baseline budgets specified by the Responsible Engineer and Project Manager. This information is calculated in both days (8 hours of work) and dollars for each work package, with a total for the entire project shown at the end.
</p>

</asp:Content>
